# Generated by Django 4.0.2 on 2022-03-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='OnDate',
            field=models.DateTimeField(default=True),
        ),
    ]
