# Generated by Django 4.0.2 on 2022-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_friendrequest_ondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='OnDate',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='IsAccepted',
            field=models.BooleanField(default=True),
        ),
    ]
