# Generated by Django 4.0.2 on 2022-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_friendrequest_ondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='IsAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
